### ISSUE TITLE
`.env` support for node preset

### ISSUE THREAD

**Issue by pi0** [nitrojs/nitro#1079]
support `.env` loading for nitro production with node preset (can be enabled with an optional flag that enables optional plugin)

**Comment by michael-bouvy** [comment]
@pi0 I'm willing to help on this ; what would be a good starting point?

Also, I guess this is not only related to `node-server` preset, it might be useful for any.

**Comment by manniL** [comment]
> Also, I guess this is not only related to `node-server` preset, it might be useful for any.

Mostly for platforms that *support* a `.env` file, which is mainly `node-server`. Other platforms (say Netlify/Vercel/...) have their own way of providing env vars.

**Comment by michael-bouvy** [comment]
> Mostly for platforms that support a .env file, which is mainly node-server. Other platforms (say Netlify/Vercel/...) have their own way of providing env vars.

All (almost) support providing environment variables (available under `process.env`) which will have precedence over `.env*` files, for instance running a Node.js server within a Kubernetes `Pod` and having environment variables configured in container spec (inline or from a `ConfigMap`/`Secret`).

**Comment by danielroe** [comment]
For anyone finding this issue, note that you can now use Node 20.6+ with `--env-file`: https://nodejs.org/docs/latest-v20.x/api/cli.html#--env-fileconfig.

**Comment by manniL** [comment]
@danielroe should we close this one as native node support landed?

**Comment by pi0** [comment]
Behavior is (sadly) yet not runtime agnostic and not backported to node 18 which we support.

**Comment by manniL** [comment]
> Behavior is (sadly) yet not runtime agnostic 

Fair, but the issue is for the *node* preset only here

> Not backported to node 18 which we support

Oh true! Hope that'll happen 🙏

**Comment by pi0** [comment]
~> #1492
