### ISSUE TITLE
Context conflict error when using `node-cluster` preset, two more windows opened using the internal IP address

### ISSUE THREAD

**Issue by alexjohndoe** [nitrojs/nitro#1116]
### Environment

- Nitro 2.3.2
- Node.js 18.14.2
- Nitro config:
```json
{
  "preset": "node-cluster"
}
```

### Reproduction

1. `nuxt.config.ts`:
```ts
export default defineNuxtConfig({
  // ...
  nitro: {
    preset: 'node-cluster', // <---- this line caused the issue
  },
})
```

2. Using the **local computer** (e.g. Mac) and **mobile device** (e.g. iPhone), using the **local network IP address** (e.g. `http://192.168.x.xxx:3000/`) opened

3. Run `npm run dev`

### Describe the bug

When using the `node-cluster` preset in the `nitro` configuration in `nuxt.config.ts`, a "Context conflict" error occurs when opening the Nuxt.js application simultaneously on a local computer (e.g., Mac) and a mobile device (e.g., iPhone) using the local network IP address (e.g., `http://192.168.x.xxx:3000/`). Disabling the `node-cluster` preset resolves the issue, but I would like to use this preset to take advantage of multi-core CPUs. I am not sure if this is a bug or a configuration issue, and I am seeking guidance on how to resolve it.

### Additional context

The issue only appears when using the `node-cluster` preset in Nuxt 3. When the preset is disabled or when using the default Nitro configuration, the issue does not occur.

### Logs

```sh
[nuxt] [request error] [unhandled] [500] Context conflict                                                                                       06:45:20
  at checkConflict (./node_modules/unctx/dist/index.mjs:6:13)  
  at Object.call (./node_modules/unctx/dist/index.mjs:31:7)  
  at contextCaller (./node_modules/nuxt/dist/app/nuxt.js:61:26)  
  at Hookable.callHookWith (./node_modules/hookable/dist/index.mjs:198:20)  
  at nuxtApp.hooks.callHook (./node_modules/nuxt/dist/app/nuxt.js:64:63)  
  at createNuxtAppServer (./node_modules/nuxt/dist/app/entry.js:30:24)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async default (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)  
  at async ./.nuxt/dev/index.mjs:777:21
```

**Comment by danielroe** [comment]
Would you provide a reproduction, please? 🙏

**Comment by Meleemaru2k** [comment]
Got the a very similar error going on since...well, I think a month by now or longer, but it went by a bit unnoticed in our team.

For us this can happen if you open multiple new tabs of different pages - say via middle-mouse click on some links on the page. This can then cause some tabs to throw this error.

We'll try to debug it new week. If we can figure something out we'll provide a reproduction.

**Comment by pi0** [comment]
This issue had been open for a long time without reproduction. If you still have the same issue and can reproduce it, please feel free to comment and reopen 👍🏼 (this seems a Nuxt-related issue)
