### ISSUE TITLE
When uploading files to the "public" directory in the production environment, the uploaded resources are not accessible.

### ISSUE THREAD

**Issue by 15844229646** [nitrojs/nitro#1269]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  yarn@1.22.4
- Builder:          vite
- User Config:      app, typescript, runtimeConfig, build, vite, nitro
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://gitee.com/WangJingXuan/new-team

### Describe the bug

In the development environment, uploading images and accessing files is working properly.

After the package is built and run, uploading images works fine, and the files are correctly written. However, when trying to access the resources, a 404 error is encountered.

Run the command: "node ./server/index.mjs."

When reproducing the issue, please run this command to ensure that the files are written to the correct directory.

**Comment by Hebilicious** [comment]
Hi @15844229646 , it appears that your repository is private. Could you provide a stackblitz/codesanbox/github reproduction please 🙏
