### ISSUE TITLE
Cannot extend nitroApp interface

### ISSUE THREAD

**Issue by eesoymilk** [nitrojs/nitro#1685]
### Environment

node v18.16.0, Nuxt 3.7.0 with Nitro 2.6.2

### Reproduction

`~/types/shim.d.ts`
```ts
import { S3Client } from '@aws-sdk/client-s3';

declare module 'nitropack' {
  interface NitroApp {
    s3: S3Client;
  }
}

export default {};
```

`~/tsconfig.json`
```json
{
  "extends": "./.nuxt/tsconfig.json",
  "files": ["./types/shim.d.ts"]
}
```

` ~/server/tsconfig.json`
```json
{
  "extends": "../.nuxt/tsconfig.server.json"
}
```

### Describe the bug

When trying to access `nitroApp.s3`, I got:
```shell
 Property 's3' does not exist on type 'NitroApp'.
```

```[tasklist]
### Tasks
```

**Comment by Hebilicious** [comment]
Hi, how are you attaching the client to the app? You are just augmenting the type definition in your description.

**Comment by enkot** [comment]
@Hebilicious 
Repro: https://stackblitz.com/edit/github-nbxfhb?file=server%2Fapi%2Ffoo.ts,server%2Findex.d.ts
For some reason it works on Stackblitz but doesn't work locally

**Comment by pi0** [comment]
The main thing is that with Nuxt, you need to install `nitropack` as a dependency to allow typescript augmenting it properly. 

Nuxt could also provide a reexport /cc @danielroe

**Comment by danielroe** [comment]
you shouldn't need to install nitropack separately on recent versions of nuxt as we do some magic to hoist the types.

check that you're fully updated

**Comment by varugasu** [comment]
I was having the same issue, but after checking `defineNitroPlugin` definition, I saw it uses:

```ts
import type { NitroAppPlugin } from "nitropack/types";
export declare function defineNitroPlugin(def: NitroAppPlugin): NitroAppPlugin;
```

So instead of using `nitropack`, I used `nitropack/types`. For @eesoymilk , it would become:

```ts
declare module 'nitropack/types' {
  interface NitroApp {
    s3: S3Client;
  }
}
```

Also, I put the `nitro.d.ts` file inside of `./server/types/nitro.d.ts`. **No changes to tsconfig.json**. 
Both my IDE (VSCode) and `pnpm nuxi typecheck` were good and showing the correct type
