### ISSUE TITLE
URL object response type for Netlify edge functions

### ISSUE THREAD

**Issue by Youhan** [nitrojs/nitro#2023]
### Describe the feature

I was not sure if this goes to H3 or Nitro. Apologies if I am confused. 

As per Netlify Edge functions documentation, the function can return a standard Response object or a URL object. 
link: https://docs.netlify.com/edge-functions/api/#overview

The URL object is used for rewrites. For example, if you want to rewrite `<username>.site.dev` to `www.side.dev/profile/<username>`,  they suggest using an edge function like this: 

```ts
export default async (req : Request) => {
  const reqUrl = new URL(req.url)
  return new URL(`/profile/${reqUrl.hostname.split('.')[0]}/${reqUrl.pathname}`, 'https://www.site.dev/')
}
```
This function does not return a Response object, instead it returns a URL object. How that would be possible with Nitro/H3?

Here are links to Netlify example and docs: 
- Docs: https://docs.netlify.com/edge-functions/api/#overview
- Rewrite example: https://github.com/netlify/edge-functions-examples/tree/main/pages/rewrite
- Rewrite Demo: https://edge-functions-examples.netlify.app/rewrite

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by serhalp** [comment]
@Youhan What are you trying to accomplish here? Nitro on Netlify will automatically turn configured redirects and rewrites into a configuration that Netlify understands, so they should work. Are you trying to return redirects/rewrites dynamically that can only be determined dynamically at runtime, hence needing to return a `URL`?

**Comment by Youhan** [comment]
Yes, that's correct. I am trying to rewrite the `www.side.dev/profile/<username>` to `<username>.site.dev` dynamically.

**Comment by pi0** [comment]
In an event handler you can use `getRequestURL` / `sendRedirect`

```js
export default eventHandler(async (event) => {
  const reqUrl = getRequestURL(event);
  const newUrl = new URL(
    `/profile/${reqUrl.hostname.split(".")[0]}/${reqUrl.pathname}`,
    "https://www.site.dev/"
  );
  return sendRedirect(event, newUrl.href);
});
```

--

In h3 v2 / nitro v3:

- You can directly use `event.url` instead of `getRequestURL(event)`
- I made a feature request to investigate possibility of supporting `return <URL>` as redirect you can follow from here: https://github.com/unjs/h3/issues/913

---
