### ISSUE TITLE
asset.maxAge not applied with `fallthrough: true`

### ISSUE THREAD

**Issue by nksaraf** [nitrojs/nitro#2253]
https://github.com/unjs/nitro/blob/b0f08c1c3b1b9e530c0ff9731aba399fd8ada0c3/src/nitro.ts#L85-L95

Looks like when `fallthrough: true`, a publicAsset's `maxAge` property is not applied, so no cache-control headers are added.

Is there a way to go around this. I need `fallthrough: true` because I want to server the `/public` dir at `/` base. But imagine i want a route rule too apply to all the public assets at `/**`, (but not the cases which fallthrough to a lower handlet). Is this not possible right now?

**Comment by amandesai01** [comment]
As I can see, it uses `defu` to apply defaults to provided routeRules. You can still pass in your own routeRules with the required headers. See: https://nitro.unjs.io/guide/routing#route-rules

**Comment by pi0** [comment]
please provide a minimal reproduction 🙏🏼

**Comment by pi0** [comment]
I think the easiest way is to explicitly add `routeRules` entries for asset path cache headers.  (nitro cannot safely assume to apply headers to paths that can fallback to other handlers)
