### ISSUE TITLE
I'm using the caching system of nitro, which use the redis driver. If my redis connection fails, is there a way to make defineCachedEventHandler not report an error and not use the cache?

### ISSUE THREAD

**Issue by robertyclin** [nitrojs/nitro#2609]
### Describe the feature

defineCachedEventHandler works normally

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by hp-vev** [comment]
I was looking into this myself and was wondering if there is a way to skip cache if the driver gives an error. If valuable I can make a reproduction it's quit simple just run nuxt and a redis instance and kill your redis instance. Happy to help impelmenting this if somebody would point me in the right direction.

**Comment by HPieters** [comment]
I was looking into this myself and was wondering if there is a way to skip cache if the driver gives an error. If valuable I can make a reproduction it's quit simple just run nuxt and a redis instance and kill your redis instance. Happy to help impelmenting this if somebody would point me in the right direction.

**Comment by bitbytebit1** [comment]
This seems like quite an important issue, I'm surprised it hasn't got any love! I would also expect that should the caching mechanism fail it should fall back to calling the function and logging the error

**Comment by cjpearson** [comment]
For a reproduction you can use the starter app and adjust the config:

```ts
// https://nitro.unjs.io/config
export default defineNitroConfig({
  srcDir: "server",
  storage: {
    redis: {
      driver: "redis",
      url: "redis://localhost:6379",
      maxRetriesPerRequest: 3, // give up sooner and return an error
    },
  },
  routeRules: {
    "/**": { cache: { maxAge: 60 * 60, base: "redis" } },
  },
});
```

**Comment by cjpearson** [comment]
@pi0 I think this can be marked as fixed
