### ISSUE TITLE
Heroku deployments hanging

### ISSUE THREAD

**Issue by AdamBD** [nitrojs/nitro#2648]
### Environment

    "nitropack": "latest"
     Resolving node version 20.x...
     Downloading and installing node 20.15.1...
     Using default npm version: 10.7.0

### Reproduction

I am doing a default deployment on heroku according to the documentation described here:

https://nitro.unjs.io/deploy/providers/heroku

### Describe the bug

Nitro is able to finish the build step  `"build": "nitro build",` but it seemingly never moves on to call the start script 
`"start": "node .output/server/index.mjs"`, then eventually the build hits the timeout and fails

### Additional context

This is my package.json 

{
  "private": true,
  "scripts": {
    "build": "nitro build",
    "start": "node .output/server/index.mjs",
    "dev": "nitro dev"
  },
  "devDependencies": {
    "nitropack": "latest"
  },
  "dependencies": {
    "@supabase/supabase-js": "^2.43.5",
    "bull": "^4.14.0",
    "dotenv": "^16.4.5",
    "ejs": "^3.1.10",
    "fluent-ffmpeg": "^2.1.3",
    "googleapis": "^140.0.1",
    "jsonwebtoken": "^9.0.2",
    "marked": "^13.0.1",
    "ofetch": "^1.3.4",
    "openai": "^4.52.7",
    "ws": "^8.18.0"
  }
}

### Logs

```sh
-----> Building on the Heroku-22 stack
-----> Using buildpack: heroku/nodejs
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):   unspecified
       engines.npm (package.json):    unspecified (use default)
       
       Resolving node version 20.x...
       Downloading and installing node 20.15.1...
       Using default npm version: 10.7.0
       
-----> Installing dependencies
       Installing node modules
       
       added 490 packages, and audited 492 packages in 6s
       
       88 packages are looking for funding
         run `npm fund` for details
       
       found 0 vulnerabilities
       npm notice
       npm notice New minor version of npm available! 10.7.0 -> 10.8.2
       npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.2
       npm notice To update run: npm install -g npm@10.8.2
       npm notice
       
-----> Build
       Running build
       
       > build
       > nitro build
       
       [nitro] ✔ Generated public .output/public
       [nitro] ℹ Building Nitro Server (preset: heroku)
       [nitro] ✔ Nitro Server built
       ----- truncated for security -----
         ├─ .output/server/chunks/runtime.mjs (297 kB) (68.8 kB gzip)
         ├─ .output/server/chunks/runtime.mjs.map (3.48 kB) (959 B gzip)
         ├─ .output/server/index.mjs (470 B) (243 B gzip)
         └─ .output/server/package.json (2.19 kB) (992 B gzip)
       Σ Total size: 32.1 MB (2.52 MB gzip)
       [nitro] ✔ You can preview this build using node .output/server/index.mjs
-----> Timed out running buildpack Node.js
Terminated
 !     Push failed
```

**Comment by AdamBD** [comment]
Can anyone help here? you cannot deploy nitro to heroku as is.

**Comment by manniL** [comment]
@AdamBD hard to tell without a full reproduction.

**Comment by pi0** [comment]
This issue had been open for a long time without reproduction. If you still have the same issue and can reproduce it, please feel free to comment and reopen 👍🏼
