### ISSUE TITLE
2.10: Can't run db code from plugins

### ISSUE THREAD

**Issue by vladkrasn** [nitrojs/nitro#2832]
### Environment

Node.js: 22
Nitro: 2.10

### Reproduction

https://stackblitz.com/edit/github-f7duzj?file=nitro.config.ts,server%2Fplugins%2Fdb.ts

### Describe the bug

`[nitro] [unhandledRejection] ReferenceError: Cannot access 'instances' before initialization`

Seems like plugin that executes SQL is run before Nitro initializes the default sqlite database.

### Additional context

Worked fine in 2.9.7

**Comment by Ponkhy** [comment]
I've been encountering a similar issue with Nuxt 3.13.2.
Unfortunately I don't have the time to create a reproduction, but here is the error I'm receiving.

```js
file:///frontend/.output/server/chunks/nitro/nitro.mjs:7293
  return base ? prefixStorage(storage, base) : storage;
                              ^
ReferenceError: Cannot access 'storage' before initialization
    at useStorage (file:///frontend/.output/server/chunks/nitro/nitro.mjs:7293:31)
    at file:///frontend/.output/server/chunks/nitro/nitro.mjs:6521:19
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
```

Overwriting the version in the `package.json` file fixes it for now.
```json
"overrides": {
  "nitropack": "2.9.7"
}
```

**Comment by pi0** [comment]
Thanks for reproduction dear @vladkrasn

I have made #2837 which particularly fixes the `useDatabase` ordering issue.

There might be more issues similar to this due to rollup wrong chunk ordering. @Ponkhy i will try to investigate however if you can make a nitro-only minimal reproduction that would be super helpful 🙏🏼

**Comment by Ponkhy** [comment]
Thank you for the quick fix @pi0!
After the update to v2.10.1 my issue has been resolved as well.
