### ISSUE TITLE
Cannot access storage/_sharedRuntimeConfig before initialization

### ISSUE THREAD

**Issue by dev-certogo** [nitrojs/nitro#2833]
### Environment

Nitro 2.10.0

### Reproduction

package.json use "nuxt": "^3.10.1", node 18.20.4

1. Run npm install
2. npm run build
3. Run node .output/server/index.mjs

### Describe the bug

Cannot start application as following error.

/prooject/frontend-nuxtjs/.output/server/chunks/nitro/nitro.mjs:8609
  return base ? prefixStorage(storage, base) : storage;
                              ^

ReferenceError: Cannot access 'storage' before initialization
    at useStorage (file:///project/frontend-nuxtjs/.output/server/chunks/nitro/nitro.mjs:8609:31)
    at file:///project/frontend-nuxtjs/.output/server/chunks/nitro/nitro.mjs:7850:19
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12)

Node.js v18.20.4

**Comment by marco-land** [comment]
I have the same issue with the error:
`ReferenceError: Cannot access '_sharedRuntimeConfig' before initialization`

**Comment by manniL** [comment]
This should be raised in the nuxt repo

**Comment by pi0** [comment]
Seems related to #2832

**Comment by pi0** [comment]
Resolved with #2839 (in nightly and for 2.10.1+)

In case of similar issues, please consider reporting using a new issue (nuxt reproduction is fine in similar issues since problem is more complex)

**Comment by dev-certogo** [comment]
Thank you all. I got it solve the patch 2.10.1+
