### ISSUE TITLE
Could not resolve entry module "node_modules/nitropack/dist/presets/node/runtime/node-cluster"

### ISSUE THREAD

**Issue by ElYaiko** [nitrojs/nitro#2840]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.15.1
- Nuxt Version:     3.13.2
- CLI Version:      3.15.0
- Nitro Version:    2.10.0
- Package Manager:  bun@1.1.34
- Builder:          -
- User Config:      default
------------------------------

### Reproduction

-

### Describe the bug

I'm trying to build my Nuxt project with preset 'node-cluster'.
It used to work, but now I'm getting the next error:

```
 Could not resolve entry module "node_modules/nitropack/dist/presets/node/runtime/node-cluster".

  at getRollupError (node_modules/rollup/dist/es/shared/parseAst.js:395:41)
  at error (node_modules/rollup/dist/es/shared/parseAst.js:391:42)
  at ModuleLoader.loadEntryModule (node_modules/rollup/dist/es/shared/node-entry.js:20057:20)
  at async Promise.all (index 0)

```

(I also can't find the file in the repo but https://github.com/nitrojs/nitro/blob/v2/src/presets/node/runtime/cluster.ts)

**Comment by pi0** [comment]
Thanks for report. will be fixed in next patch (and nightly channel shortly)
