### ISSUE TITLE
Issue with Nitropack 2.10.0 causing build failure in Nuxt project:

### ISSUE THREAD

**Issue by tobychidi** [nitrojs/nitro#2843]
### Environment

**Environment**:
- Operating System: Windows_NT
- Node Version: v20.18.0
- Nuxt Version: 3.13.2
- CLI Version: 3.15.0
- Nitro Version: 2.9.7
- Package Manager: pnpm@9.12.3
- Builder: -
- User Config: default
- Runtime Modules: @nuxt/ui@3.0.0-alpha.7, @pinia/nuxt@0.6.1, @nuxt/image@1.8.1, @vueuse/nuxt@11.2.0, nuxt-gtag@3.0.1, @nuxt/eslint@0.6.1, @nuxtjs/leaflet@1.2.3
- Build Modules: -

### Reproduction

**Reproduction**:
1. Ensure Nitropack is updated to 2.10.0 `in my case was after pnpm up --latest`
2. Run the build command for the Nuxt project

### Describe the bug

After updating Nitropack to version 2.10.0, my Nuxt project fails to build with the error `[worker reload] [worker init] C:/Users/tobychidi/Documents/GitHub/kaycee/Rotabliss/.nuxt/dev/index.mjs failed`.

This happens after `pnpm up --latest` and `pnpm dev`

### Additional context

**Expected Result**:
The project should build successfully without errors.

**Actual Result**:
The build fails with the error mentioned above.

**Additional Information**:
- No recent changes were made to the project before updating Nitropack.
- Revertint to v2.9.7 fixed the issue

**Comment by pi0** [comment]
Can you please recreate your project lockfile (by removing `pnpm-lock.yml` and try again? It should show `2.10.1` in both `nuxi info` and the `nuxt dev` banner.

**Comment by tobychidi** [comment]
Just updated to `v2.10.2`. The issue has been fixed.

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.18.0
- Nuxt Version:     3.13.2
- CLI Version:      3.15.0
- Nitro Version:    2.10.2
- Package Manager:  pnpm@9.12.3
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/ui@3.0.0-alpha.7, @pinia/nuxt@0.7.0, @nuxt/image@1.8.1, @vueuse/nuxt@11.2.0, nuxt-gtag@3.0.1, @nuxt/eslint@0.6.1, @nuxtjs/leaflet@1.2.3
- Build Modules:    -
