### ISSUE TITLE
Inaccurate return type of defineCacheFunction (typescript)

### ISSUE THREAD

**Issue by tobychidi** [nitrojs/nitro#2847]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.18.0
- Nuxt Version:     3.14.0
- CLI Version:      3.15.0
- Nitro Version:    2.10.2
- Package Manager:  pnpm@9.12.3
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/ui@3.0.0-alpha.7, @pinia/nuxt@0.7.0, @nuxt/image@1.8.1, @vueuse/nuxt@11.2.0, nuxt-gtag@3.0.1, @nuxt/eslint@0.6.1, @nuxtjs/leaflet@1.2.4
- Build Modules:    -
------------------------------

### Reproduction

use `defineCacheFunction`

### Describe the bug

The return type of defineCacheFunction appears to have changed from `T` to `T | undefined`, which is a breaking change. This utility should accurately reflect the return type of the wrapped function. The issue arose following the recent update to `v3.10`.

### Additional context

I have yet to grasp the reason behind this change. Moreover, if the change was deliberate, it was not documented accordingly.

**Comment by pi0** [comment]
Thanks for report. Should be fixed in nightly and next release.
