### ISSUE TITLE
ignore is not working

### ISSUE THREAD

**Issue by MickL** [nitrojs/nitro#2863]
### Environment

Nitro: 2.10.4
Bun: 1.1.34
Node: 22.11.0

### Reproduction

- https://github.com/MickL/nitro-bug-ignore
- https://stackblitz.com/~/github.com/MickL/nitro-bug-ignore

### Describe the bug

In Nuxt we can set `ignore` array within nuxt.config.ts. In Nitro there seems to be the same option but it does nothing:

```ts
export default defineNitroConfig({
  ignore: ['/dev-only'],
});
```

### Additional context

I want to disable some routes in product that are only for development.

**Comment by pi0** [comment]
`ignore` is an array for glob patterns. Nitro uses `glob` option for ignore scan patterns (plugins, routes, etc) + static assets.

This works on sandbox:

```js
//https://nitro.unjs.io/config
export default defineNitroConfig({
  ignore: ['routes/dev-only/**'],
  compatibilityDate: '2024-11-08'
});
```

**Comment by pi0** [comment]
PS: Nitro 2.10 supports `.dev` prefix in files to automatically exclude them from production :)

**Comment by MickL** [comment]
> PS: Nitro 2.10 supports `.dev` prefix in files to automatically exclude them from production :)

Thats amazing! Does it work also in Nuxt with pages/components/assets or is it Nitro exlusive?

**Comment by pi0** [comment]
The suffix is supported file-level -- but you can programmatically also add conditions flag to `nitro.options.handlers`

Nuxt has [`<DevOnly>`](https://nuxt.com/docs/api/components/dev-only) i can't recall TBH but i _guess_ it did add support for `.dev` for components, if not maybe worth making a proposal for Nuxt.

Shalll i close this issue? (please feel free to use discussions or [discord](https://discord.nitro.build) always!)

**Comment by MickL** [comment]
```
'routes/dev-only/**'
```

Did the trick, thanks! The ignore option should be documented :)
