### ISSUE TITLE
update open api docs

### ISSUE THREAD

**Issue by de-n3xus** [nitrojs/nitro#2867]
### Environment

Node Version: v20.16.0
Nitro Version: v2.10.4

### Reproduction

Go to https://stackblitz.com/edit/github-fvcvgg?file=nitro.config.ts and try to open 
`/_nitro/openapi.json`
`/_nitro/scalar`
`/_nitro/swagger`

### Describe the bug

Nitro config has enabled openAPI in experimental section, but openapi routes is not found
Nothing in logs

`/server/api/test.ts` contains this
```ts
defineRouteMeta({
  openAPI: {
    tags: ["test"],
    description: "Test route description",
    parameters: [{ in: "query", name: "test", required: true }],
  },
});

export default defineEventHandler(() => "OK");
```

**Comment by de-n3xus** [comment]
omg
https://github.com/nitrojs/nitro/blob/8c934c93ac29bf016858a0a6eff56504821c7b34/src/core/config/resolvers/open-api.ts#L24
https://github.com/nitrojs/nitro/blob/8c934c93ac29bf016858a0a6eff56504821c7b34/src/core/config/resolvers/open-api.ts#L34
https://github.com/nitrojs/nitro/blob/8c934c93ac29bf016858a0a6eff56504821c7b34/src/core/config/resolvers/open-api.ts#L44

why its not in docs...

**Comment by Exotelis** [comment]
I opened https://github.com/nitrojs/nitro/pull/2869

**Comment by Exotelis** [comment]
> Thanks for docs PR. Please note that the defaults and behavior might change while this feature is in experimental state (we communicate them via release notes)

This is absolutely fine, but please ensure the documentation stays up to date. It becomes challenging to use features and contribute effectively if the docs are outdated.
