### ISSUE TITLE
netlify preset: [nuxt] [request error] [unhandled] [500] Cannot find module '@vue/devtools-api'

### ISSUE THREAD

**Issue by peralta** [nitrojs/nitro#2874]
### Environment

Nitro v2.10.3
Nuxt v3.14.159

### Reproduction

1. Deploy nuxt project using `netlify` preset
2. Access non pre-rendered route

### Describe the bug

Deployed nitro server using `netlify` preset fails on first request with
```
Nov 11, 11:07:42 PM: 7182da0a ERROR  [nuxt] [request error] [unhandled] [500] Cannot find module '@vue/devtools-api'
Require stack:
- /var/task/.netlify/functions-internal/server/server.mjs
```
Error changes on second request to:
```
Nov 11, 11:08:02 PM: c36ce405 ERROR  [nuxt] [request error] [unhandled] [500] _createApp is not a function
```

### Additional context

See https://answers.netlify.com/t/functions-cannot-find-module-vue-devtools-api/129081/2 -- they solved the issue by downgrading nitro.

Installing `@vue/devtools-api` package does not fix the issue.

Error does not happen using `netlify-legacy` preset.

Error does not happen when using `nuxt dev`, only when built and deploying in production. Building for production (`nuxt build`) and running function server locally (`netlify functions:serve -f .netlify/functions-internal`) works.

**Comment by peralta** [comment]
I managed to solve the issue by explicitly adding the `vue` and `vue-router` as dependencies to my nuxt project (https://github.com/nuxt/nuxt/commit/e473aff58f88e881adeea9a58bf3f136866c29d7 made me check).

**Comment by richgcook** [comment]
@danielroe Any suggestions? :)

**Comment by shaojiaqi08** [comment]
I encountered the same issue. Despite having `vue-router:latest` in the project dependencies, the problem persisted. Then, I removed the `.output/server/node_modules`, ran `npm i`, and it seems the issue has been fixed.

**Comment by adrianrudnik** [comment]
Had the same with a project, deployed via rsync without the `-a` flag, so some symlinks were missing.

```shell
.output/server/node_modules/pinia/node_modules/@vue/devtools-api -> ../../../.nitro/@vue/devtools-api@7.7.2
```
