### ISSUE TITLE
not starting with Deno 2.0.6

### ISSUE THREAD

**Issue by zenwork** [nitrojs/nitro#2878]
### Environment

I am running on MacBook Pro with Deno 2.0.6

### Reproduction

I followed the guide to run with Deno.

Did this:
```
deno run -A npm:giget@latest nitro nitro-app --install
cd nitro-app
deno run dev
```

### Describe the bug

The server is crashing on startup

output:
```
❯ deno run dev                                                                    
Task dev nitro dev

  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'pathname')
    at getPathname (ext:deno_node/_fs/_fs_stat.ts:177:49)
    at ext:deno_node/_fs/_fs_stat.ts:151:13
    at eventLoopTick (ext:core/01_core.js:175:7)
```

the same install works fine if I run with node

**Comment by yevklim** [comment]
@zenwork This seems like a bug in Deno, specifically how it processes `scripts` from `package.json`. So, someone should open an issue in Deno's repository.

But we have a workaround. It also works in other frameworks using Nitro, e.g., Nuxt.

1. Create `deno.json`:
```json
{
  "nodeModulesDir": "auto"
}
```
2. Then copy `scripts` from `package.json` into `deno.json` as `tasks`. In this case:
```json
{
  "tasks": {
    "build": "nitro build",
    "dev": "nitro dev",
    "prepare": "nitro prepare",
    "preview": "node .output/server/index.mjs"
  },
  "nodeModulesDir": "auto"
}
```
3. (optional) You might want to remove `scripts` from `package.json`. But it doesn't have any effect at the moment.

This workaround also works in other frameworks that use Nitro, e.g., Nuxt.
