### ISSUE TITLE
proxy issues with `accept-encoding` (zstd)

### ISSUE THREAD

**Issue by wug-ge** [nitrojs/nitro#2880]
### Environment

Node v22.1.0
nitropack@2.10.4

### Reproduction

Create new Project, add the following to nitro.config.ts:
`routeRules: {
  "/api/**": { proxy: "https://jsonplaceholder.typicode.com/**" },
},`

### Describe the bug

I'm not sure what reproduces this, but it seems to be affected by some kind of race condition given the result is not always the same.

When I call http://localhost:3000/api/todos/1 with this setting, I get back

502 Bad Gateway
Bad Gateway

at createError (./node_modules/h3/dist/index.mjs:78:15)
...

or a 200 response with some kind of encoded string/binary data? (see attached screenshot)
![image](https://github.com/user-attachments/assets/2a552c63-6f40-4a47-90e9-c47d59d08f21)

In my tests, it seems to be happening ONLY with https requests, http requests work fine.

### Additional context

Let me know if you need any more information.

**Comment by gxres042** [comment]
This link can only get a vaild JSON data by ofetch:

``` ts
// server/api/todos/[slug]/index.ts
export default defineEventHandler(async (event) => {
    const slug = getRouterParam(event, "slug");
    return await $fetch(
        `https://jsonplaceholder.typicode.com/todos/${slug}`
    );
});
```

I think it looks like the target link is blocking the proxy.

**Comment by pi0** [comment]
Issues is probably related to proxied encoding headers. using curl also things work.

**Comment by wug-ge** [comment]
I did some debugging, interestingly requests to https://jsonplaceholder.typicode.com/todos are successful while those to https://jsonplaceholder.typicode.com/todos/1 (specific todo) fail.

I found out that removing "zstd" in the Accept-Encoding header in the proxy solves this issue, maybe this is helpful.

**Comment by pi0** [comment]
Came to the same result same time haha, yes we might need to filter `accept-encoding` in [h3 sendProxy util](https://github.com/unjs/h3/blob/e25215d6e4b64f57abd32d2117a541281360a46b/src/utils/proxy.ts#L25). I'm wondering if it is limitation of Undici fetch (node.js fetch)...

**Comment by pi0** [comment]
I think safest is to ignore it altogether, similar cases might happen in the future / for other runtimes: https://github.com/unjs/h3/pull/914

thanks for report ❤️
