### ISSUE TITLE
Duplicated entries in _headers

### ISSUE THREAD

**Issue by GreyXor** [nitrojs/nitro#2909]
### Environment

Nitro v2.10.4
Nuxt v3.14.1592

### Reproduction

pnpm build --preset=cloudflare-pages-static

### Describe the bug

The _headers file contains dupplicated entries. This creates a _headers file like this, for example:

/settings
  x-frame-options: DENY
/*
  X-Frame-Options: DENY
  
  So during my HTTP requests. if I go to /settings. I get two `x-frame-options: DENY` requests.

**Comment by pi0** [comment]
can you share a URL/screenshot of deployment + nuxt/nitro config?

**Comment by GreyXor** [comment]
sadly I cannot share url nor demo :/
maybe you can have more details here: https://github.com/nuxt-modules/security/issues/575

I saw that in devmode I don't have this issue

**Comment by pi0** [comment]
it might be an issue with that module+vendor, I suggest tracking via https://github.com/nuxt-modules/security/issues/575.
