### ISSUE TITLE
Nuxt and Sentry not working with Prisma as a linked NPM package

### ISSUE THREAD

**Issue by rocketiscool** [nitrojs/nitro#2911]
### Environment

Nitro - 2.10.4 
Node.js - v20.14.0

### Reproduction

Steps:

1. Setup Nuxt
2. Setup a Typescript NPM Prisma Package with a custom generator output e.g output = "../src/generated/client"
3. Link the package to Nuxt

### Describe the bug

No idea why, only on latest sentry/nuxt and nuxt versions I've encounted this issue

I've opened up an issue in Nuxt already at [#29882](https://github.com/nuxt/nuxt/issues/29882) but it was closed so I had to do some debugging to figure out the issue myself.

I've setup a new Nuxt project and done the reproduced steps and encounter this issue ONLY when the package is linked in development mode, when I unlink the package for production and use the actual npm package it works.

This is an issue only because I have to keep unlinking and unhashing sentry/nuxt from my modules every time I want to deploy and want to use Sentry.

Was not like this originally used to work fine, could someone find out a workaround or a potential fix? Thanks!

**Comment by pi0** [comment]
Can you please share a reproduction project or stackblitz? 🙏🏼

**Comment by rocketiscool** [comment]
> Can you please share a reproduction project or stackblitz? 🙏🏼

Issue only occurs with local linked packages, not too familiar if that's possible with reproductions

**Comment by pi0** [comment]
- Without minimal reproduction, it is tough to know this is an issue with Nitro
- Linked packages are often prone to such issues.
- Sentry SDK for Nuxt uses a [very unsafe hack](https://github.com/getsentry/sentry-javascript/blob/develop/packages/nuxt/src/vite/addServerConfig.ts) to make it work with Nitro today, if issue occurs only with sentry, it is very likely related and sadly nothing we can do here for it (in meantime I am in contact and trying to push for better way)
