### ISSUE TITLE
`getRouteRules` incorrect type

### ISSUE THREAD

**Issue by moshetanzer** [nitrojs/nitro#2939]
### Environment

nuxt latest

### Reproduction

https://stackblitz.com/edit/github-bcfr8dys?file=app.vue

Navigate in IDE to `api/test` and you will see `ts` complains that it wants `url: string` to be passed to `getRouteRules()` but obviously works correctly (to see navigate in browser to /api/test) when passing event (which it always used to be and should be!)

### Describe the bug

When using `getRouteRules` even when importing from virtual `#imports` getting the following type error:

```
getRouteRules(url: string): Promise<Record<string, any>>  @since — 3.7.4
```

Pretty sure this is a new issue, didn't get it a few weeks ago - though may be a `nuxt` issue 🤔 since as far as I can see in nitro seems to expect H3Event!

Thanks!

**Comment by danielroe** [comment]
yes, this is an effect of the Nuxt composable and needs to be fixed downstream.
