### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by Makkalay** [nitrojs/nitro#2957]
### Environment

Nitro site

### Reproduction

https://nitro.build/guide/routing#simple-middleware

### Describe the bug

> You can define route handler meta at build-time using defineRouteMeta micro in the event handler files.
Need to correct micro to macro I think?

**Comment by Makkalay** [comment]
Also on https://h3.unjs.io/guide/event#eventmethod i see enumerating what is context, handled and  headers two time.
At least in section about [event.path](https://h3.unjs.io/guide/event#eventpath) is wroten something about other things like context?

[event.path](https://h3.unjs.io/guide/event#eventpath)
Access to the request path. (Example: /test?test=123)

context with some context information about the request.
headers with a normalized version of the headers of the request.
handled with a boolean that indicates if the request has terminated.

**Comment by pi0** [comment]
thnx. nitro typo fixed in f5ebb254327cfc577198584071f803ff2c8db432 and feel free to open a PR to remove duplicate lines in h3 docs.

**Comment by Makkalay** [comment]
like so https://github.com/unjs/h3/pull/938/files ?

**Comment by Makkalay** [comment]
no [event.node](https://h3.unjs.io/guide/event#eventnode) and event.web

**Comment by pi0** [comment]
Thanks for PR. Not sure to get your second q, please feel free to reach out to me via discord `@pi0` or x/bsky/email (on my github profile)

**Comment by Makkalay** [comment]
![image](https://github.com/user-attachments/assets/791dc53e-e5a5-4935-bdeb-81d404e249ba)
differ 
![image](https://github.com/user-attachments/assets/cece6d9d-fd93-407a-a7cb-9d4d88df733c)

**Comment by pi0** [comment]
See my comment: https://github.com/unjs/h3/pull/938 (your PR updated [v3 docs](https://main.unjs-h3.pages.dev/guide/event-handler)) you need to update h3 `v2` branch.

(also please consider using discussions or DM, this is an unrelavant issue in nitro)
